[config]
publish_output = true

[pr_reviewer]
num_max_findings = 4
require_tests_review = true
require_security_review = true
persistent_comment = true
final_update_message = false

[pr_code_suggestions]
num_code_suggestions_per_chunk = 4
persistent_comment = true

[pr_description]
persistent_comment = true
